train: # 训练
  # Path related arguments
  checkpoint_dir: 'log/vis/source_only/gta5/gta5_vgg_error-val/'   # val日志路径
  model_file: 'log/train/source_only/gta5/gta5_vgg_error-val/gta5final.pth'                          # 预热模型路径
  backbone: 'vgg16'                         # vgg16 resnet101
  data_name: 'cityscapes'                   # 可选：gta5, synthia, cityscapes
  num_classes: 19                           # gta5为19, synthia为16

  # dataloder
  batch_size: 1
  num_workers: 2
  pin_memory: True                            # 当计算机的内存充足的时候，可以设置pin_memory=True。当系统卡住，或者交换内存使用过多的时候，设置pin_memory=False。

  # other
  flip: True                                  # 是否使用翻转预测
  evl_with_original: True                     # 原始尺寸预测还是输出尺寸预测

  # keep default  必要的参数，参数不影响，但是必须提供。
  imagenet_pretrained: False
  use_pseudo: False
  color_jitter: False                          # 色彩抖动数据增强
  gaussian_blur: False                         # 高斯模糊数据增强
  random_mirror: False                         # 随机镜像数据增强
  lr: 0.001

  # dataset related arguments
  cityscapes:
    resize: True
    size: 1024,512                                                        # cityscapes常用的尺寸
    image_dir: 'F:/dataset/cityscape/leftImg8bit'                         # RGB图像文件夹
    label_dir: 'F:/dataset/cityscape/gtFine'                              # label标签路径。方便在使用伪标签的时候，修改为伪标签路径

  gta5:
    resize: True
    size: 1280,720                                                        # gta5常用尺寸
    image_dir: '/home/lyc/data/gta5/images'                               # RGB图像文件夹
    label_dir: '/home/lyc/data/gta5/labels'                               # label标签路径

  synthia:
    resize: False                                                         # synthia原始尺寸就是1280,760
    size: 1280,760                                                        # gta5常用尺寸
    image_dir: 'F:/dataset/RAND_CITYSCAPES/RGB'                           # RGB图像文件夹
    label_dir: 'F:/dataset/RAND_CITYSCAPES/GT/LABELS'                     # label标签路径


