train: # 训练
  # Path related arguments
  checkpoint_dir: './log/train/UDA/synthia/synthia_vgg16_use_uncertainty'

  # Model related arguments
  backbone: 'vgg16'
  batch_size: 1
  warmup_model_file: 'log/train/source_only/synthia/synthia_vgg/synthiabest.pth'                 # 预训练模型路径（不是imagenet预训练模型）
  imagenet_pretrained: True                   # 是否用imagenet预训练模型初始化模型
  save_inter_model: True                      # 是否保存中间训练的模型

  # train related arguments
  seed: 12345                                 # 随机数种子，用于实验复现
  gpu_id: "0"
  num_workers: 4
  pin_memory: True                            # 当计算机的内存充足的时候，可以设置pin_memory=True。当系统卡住，或者交换内存使用过多的时候，设置pin_memory=False。
  iter_max: 200000                            # the max num of iteration
  iter_stop: 100000                           # the early stop step
  iter_epoch: 5000                            # the num of iteration in one epoch
  iter_show_loss: 1000                        # the num of iteration of print train loss

  # UDA related arguments
  round_num: 5                                # 迭代的轮数。每一轮会生成一次新的伪标签
  init_round: 0                               # 初始化的轮数
  epoch_each_round: 2                         # 每轮迭代的次数
  deque_capacity_factor: 1.0                  #
  thing_type: 'Entropy'                       # ['Entropy', 'Squares','Cosine']
  entropy_type: 'Entropy'                     # ['Entropy', 'Squares', 'FocalEntropy']
  norm_order: 1                               # L1、L2...
  lambda_things: 1                            # things alignment loss 权重
  lambda_stuff: 1                             # stuff alignment loss 权重
  lambda_entropy: 1                           #
  centroid_smoothing: 0.9                     # 类中心移动指数平均的平滑系数
  use_uncertainty: True                       # 是否使用不确定性伪标签

  # dataset related arguments
  source_data_name: 'synthia'                    # ['gat5', 'synthia']
  target_data_name: 'cityscapes'              # cityscapes
  num_classes: 16
  use_pseudo: False                           # 是否使用伪标签，只对cityscapes有用
  ignore_label: -1                            # 忽略的标签
  color_jitter: True                          # 色彩抖动数据增强
  gaussian_blur: True                         # 高斯模糊数据增强
  random_mirror: True                         # 随机镜像数据增强

  cityscapes:
    resize: True
    size: 1024,512                                                            # cityscapes常用的尺寸
    image_dir: '/home/lyc/data/cityscape/leftImg8bit'                         # RGB图像文件夹
    label_dir: '/home/lyc/data/cityscape/gtFine'                              # label标签路径。方便在使用伪标签的时候，修改为伪标签路径

  gta5:
    resize: True
    size: 1280,720                                                            # gta5常用尺寸
    image_dir: '/home/lyc/data/gta5/images'                                   # RGB图像文件夹
    label_dir: '/home/lyc/data/gta5/labels'                                   # label标签路径

    use_trans_image: False                                                    # 是否使用图像翻译后GTA5数据集
    trans_image_dir: '/home/lyc/data/gta5_deeplab/images'            # 图像翻译的图像文件夹，如不设置不使图像翻译数据集，可以忽略

  synthia:
    resize: False                                                             # synthia原始尺寸就是1280,760
    size: 1280,760
    image_dir: '/home/lyc/data/RAND_CITYSCAPES/RGB'                           # RGB图像文件夹
    label_dir: '/home/lyc/data/RAND_CITYSCAPES/GT/LABELS'                     # label标签路径

    use_trans_image: True                                                    # 是否使用图像翻译后GTA5数据集
    trans_image_dir:  '/home/lyc/data/syn_deeplab/RGB'                        # 图像翻译的图像文件夹，如不设置不使图像翻译数据集，可以忽略

  # optimization related arguments
  optim: 'SGD'                                # SGD or Adam
  lr: 0.00025                                 # learning rate
  beta: 0.5                                   # Adam optimizer hyper parameter
  momentum: 0.9                               # SGD optimizer hyper parameter
  weight_decay: 0.0005                        # optimizer hyper parameter
  poly_power: 0.9                             # poly_power




