train: # 训练
  # Path related arguments
  exp_name: 'gta5_vgg'
  log_dir: './log/train/Source_only/gta5'
  checkpoint_dir: ''                            # checkpoint_dir = log_dir + exp_name

  # Model related arguments
  backbone: 'vgg16'
  batch_size: 1
  pretrained_model_file: None                 # 预训练模型路径（不是imagenet预训练模型）
  imagenet_pretrained: True                   # 是否用imagenet预训练模型初始化模型
  save_inter_model: True                      # 是否保存中间训练的模型

  # train related arguments
  seed: 12345                                 # 随机数种子，用于实验复现
  gpu_id: "0"
  num_workers: 4
  pin_memory: True                            # 当计算机的内存充足的时候，可以设置pin_memory=True。当系统卡住，或者交换内存使用过多的时候，设置pin_memory=False。
  iter_max: 200000                            # the max num of iteration
  iter_stop: 100000                           # the early stop step
  iter_epoch: 5000                            # the num of iteration in one epoch
  iter_show_loss: 1000                        # the num of iteration of print train loss

  # UDA related arguments
  round: 5                                    # 迭代的轮数。每一轮会生成一次新的伪标签
  round_num: 2                                # 每轮迭代的次数
  deque_capacity_factor: 1.0                  #
  thing_type: 'Entropy'                       # ['Entropy', 'Squares','Cosine']
  entropy_type: 'Entropy'                     # ['Entropy', 'Squares', 'FocalEntropy']
  norm_order: 1                               # L1、L2...
  lambda_things: 1                            # things alignment loss 权重
  lambda_stuff: 1                             # stuff alignment loss 权重
  lambda_entropy: 1                           #
  centroid_smoothing: 0.9                     # 类中心移动指数平均的平滑系数
  use_uncertainty: True                       # 是否使用不确定性伪标签

  # dataset related arguments
  source_data_name: 'gta5'                    # ['gat5', 'synthia']
  target_data_name: 'cityscapes'              # cityscapes
  num_classes: 19
  use_pseudo: False                           # 是否使用伪标签，只对cityscapes有用
  ignore_label: -1                            # 忽略的标签
  color_jitter: True                          # 色彩抖动数据增强
  gaussian_blur: True                         # 高斯模糊数据增强
  random_mirror: True                         # 随机镜像数据增强

  cityscapes:
    resize: True
    size: 1024,512
    image_dir: '/home/haol/data/Dataset/公开数据集/cityscape/leftImg8bit'
    label_dir: '/home/haol/data/Dataset/公开数据集/cityscape/gtFine'                  # 生成伪标签的时候，这个路径要会改伪标签所在的文件夹

  gta5:
    resize: True
    size: 1280,720
    use_trans_image: False                                                           # 是否使用图像翻译后GTA5数据集
    image_dir: '/home/haol/data/Dataset/公开数据集/GTA5/images'                       # GTA5图像文件夹
    trans_image_dir: '/home/haol/data/Dataset/公开数据集/gta5_deeplab/images'         # 图像翻译后GTA5图像文件夹
    label_dir: '/home/haol/data/Dataset/公开数据集/GTA5/labels'                       # GTA5标签文件夹

  synthia:
    resize: True
    size: 1280,760
    use_trans_image: False                                                          # 是否使用图像翻译后synthia数据集
    image_dir: '/home/haol/data/Dataset/公开数据集/RAND_CITYSCAPES/RGB'               # synthia图像文件夹
    trans_image_dir: '/home/haol/data/Dataset/公开数据集/RAND_CITYSCAPES/RGB'         # 图像翻译后synthia图像文件夹
    label_dir: '/home/haol/data/Dataset/公开数据集/RAND_CITYSCAPES/GT/LABELS'         # synthia标签文件夹


  # optimization related arguments
  optim: 'SGD'                                # SGD or Adam
  lr: 0.00025                                 # learning rate
  beta: 0.5                                   # Adam optimizer hyper parameter
  momentum: 0.9                               # SGD optimizer hyper parameter
  weight_decay: 0.0005                        # optimizer hyper parameter
  poly_power: 0.9                             # poly_power




